V22F-109 Visual Recording
red-panda-productions/DAISI pull request #208
Opened 2022-06-06 14:23 UTC by suppergerrie2

Adds a button that allows the user to watch recordings back

2022-06-09 09:28 UTC, noutheesink approved these changes
Backend seems to be correct

2022-06-09 15:07 UTC, larsdekwant requested changes
- Some style changes
- Sometimes the game stops receiving data from the blackbox. if you pause the game, it is stuck on `IPC_OK(m_server.AwaitData(m_buffer, SBB_BUFFER_SIZE), "Failed to receive data");` in SocketBlackBox::GetDecisions() 
- This error is hard to reproduce, so i'm not sure what we will do with this? Maybe add a bug report for later? Seems like an IPCLib issue.

2022-06-09 15:07 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/FileDialogManager.cpp
> +bool SelectFile(char* p_buf, char* p_err, bool p_folder, const wchar_t** p_names, const wchar_t** p_exts, int p_extCount, bool p_linuxDirectories)
Missing new param in documentation

2022-06-09 15:07 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/FileDialogManager.cpp
> +bool SelectFile(char* p_buf, char* p_err, bool p_folder, const wchar_t** p_names, const wchar_t** p_exts, int p_extCount, bool p_linuxDirectories)
missing new param in documentation

2022-06-09 15:07 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/RecorderTests.cpp
> +    SetupSingletonsFolder();                                                                \
ASSERT_TRUE for setupsingletonsfolder

2022-06-09 15:10 UTC, suppergerrie2 commented on speed-dreams/source-2.2.3/data/config/raceman/replay_visual.xml
> +      <attstr name="name" val="test_highway"/>
It's overridden before it's used, it doesn't matter what's in it

2022-06-17 12:53 UTC, larsdekwant approved these changes

2022-06-17 16:21 UTC, merged