V22F-875 Internal meta data
red-panda-productions/DAISI pull request #209
Opened 2022-06-07 08:40 UTC by noutheesink

Opens meta data buffer file after saving, if buffer exists. Saves trial ID in buffer file. Shuts down black box after saving to database

2022-06-08 15:32 UTC, larsdekwant requested changes

2022-06-09 06:51 UTC, KungFuDonkey approved these changes
Can't find anything next to what @larsdekwant has said, so if that is changed I would approve, so I approve now

2022-06-09 09:13 UTC, KungFuDonkey approved these changes

2022-06-10 08:23 UTC, larsdekwant requested changes

2022-06-10 08:23 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backend/SQLDatabaseStorage.cpp
> +#define META_BUFFER_FILENAME "sda_blackbox_internal_metadata_buffer.bin"
Move this to `ConfigEnums.h`, this is where I defined all the other buffer files as well, this also allows usage in multiple files.

2022-06-10 08:23 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/simulatedDrivingAssistance/backendUnitTests/SQLDatabaseStorageTests.cpp
> +    bufferPath.append("sda_blackbox_internal_metadata_buffer.bin");
Replace this once you moved it to `ConfigEnums.h`. This makes sure that there can never be a miss-match between these two hardcoded filenames.
```suggestion
    bufferPath.append(META_BUFFER_FILENAME);
```

2022-06-13 08:24 UTC, larsdekwant reviewed
Resolve merge conflicts first

2022-06-13 13:30 UTC, larsdekwant approved these changes
Seems to work correctly, only issue is that this will always get saved no matter what, but I guess that's fine since it was a last moment request from the client...

2022-06-14 07:50 UTC, merged