V22F-720 Edited hints + changed layout endscreen
red-panda-productions/DAISI pull request #213
Opened 2022-06-09 09:32 UTC by MaikVink

(Eva's branch)
This branch checks the hints for the use of speed dreamy terms.
It also adds labels to the certificate buttons to make them more clear.
The generate button in the init of researcher menu is put in front of the apply for easy keyboard navigation

2022-06-09 15:36 UTC, larsdekwant requested changes
The following hints should be updated (in DatabaseSettingsMenu.xml)
- CACertDialog
- PublicCertDialog
- PrivateCertDialog

The hin for 'No, dont save' should be updated to start with a capital letter, same for the two hints on the menu after that.

2022-06-10 08:08 UTC, larsdekwant requested changes
Missing documentation on newly added parameters and make sure to run clang-format on the 3 files suggested by the bot.

2022-06-10 08:08 UTC, larsdekwant commented on speed-dreams/source-2.2.3/src/modules/userinterface/legacymenu/mainscreens/DatabaseConnectionManager.cpp
> +void SetUseSSL(tCheckBoxInfo* p_info, void* p_scrHandle, int p_caControl, int p_publicControl, int p_privateControl,
missing new parameters in documentation

2022-06-10 11:08 UTC, larsdekwant approved these changes

2022-06-13 08:30 UTC, suppergerrie2 approved these changes

2022-06-13 08:31 UTC, suppergerrie2 requested changes
Add changes to Code changes document

2022-06-14 13:23 UTC, merged