V22F-883 elevation highway and speed zones
red-panda-productions/DAISI pull request #219
Opened 2022-06-13 13:14 UTC by sjoeman1

Cas added the new tracks, the elevation highway and the old highways with different speed zones

2022-06-14 09:31 UTC, larsdekwant requested changes
- Elevation Highway 100km/h name is slightly too long to fit in the environment selection controls.
- The speed zones category only has 3 selectable tracks, of which one is 'small simple road', which says nothing about speed zones. You added 4 tracks, so something went wrong here.

2022-06-15 14:40 UTC, larsdekwant requested changes
Elevation highway still only has 3 available tracks

2022-06-15 15:13 UTC, larsdekwant approved these changes

2022-06-16 13:14 UTC, suppergerrie2 requested changes
Add tracks to installer (packaging/speed-dreams-base.nsi line 224/225 gives an example)

2022-06-16 18:16 UTC, merged