V22F-942 broken installer
red-panda-productions/DAISI pull request #227
Opened 2022-06-15 10:39 UTC by suppergerrie2

2022-06-17 13:32 UTC, larsdekwant requested changes

2022-06-17 20:11 UTC, larsdekwant requested changes
add changes to packaging and speed-dreams CMake files to CHANGES.txt

2022-06-19 11:47 UTC, noutheesink approved these changes

2022-06-19 14:35 UTC, KungFuDonkey approved these changes

2022-06-19 15:06 UTC, larsdekwant approved these changes

2022-06-19 15:07 UTC, merged