V22F-815 Fix key controls in all menus
red-panda-productions/DAISI pull request #235
Opened 2022-06-18 09:51 UTC by shoekzema

Added default key controls to the options menus
Added 'Esc' key to go back to Database Connection Menu and Researcher Menu
Fixed the press Enter in EndOfExperiment Screen
Changed the order the key controls go in (except for the keybindings in controls, cause you either have to hardcode it (which is not maintainable) or rewrite like 50 files)
Swapped the positions of 'Yes, quit' and 'No, go back' in the Quit screen.

2022-06-18 12:34 UTC, larsdekwant requested changes
- Order on controlconfig menu is incorrect (skips certain options, then goes back to them later)
- Apply, Calibrate and Canel button don't need to show box on controlconfig menu, they are already highlighted.
- Forcefeedback menu order incorrect.

2022-06-18 12:34 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/controlconfigmenu.xml
> +		<attstr name="show box" val="yes"/>
```suggestion
		<attstr name="show box" val="no"/>
```

2022-06-18 12:34 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/controlconfigmenu.xml
> +		<attstr name="show box" val="yes"/>
```suggestion
		<attstr name="show box" val="no"/>
```

2022-06-18 12:34 UTC, larsdekwant commented on speed-dreams/source-2.2.3/data/data/menu/controlconfigmenu.xml
> +		<attstr name="show box" val="yes"/>
```suggestion
		<attstr name="show box" val="no"/>
```

2022-06-19 11:01 UTC, suppergerrie2 requested changes
On the control menu the order is wrong:
Left steer => Right Steer => throttle => brake => (E brake => speed limiter) => clutch => abs => tcs => [speed limiter] => light => (Left glance => right glance) => reverse gear => neutral gear => Down shift => up shift => [e brake] => [left glance] => [right glance] => intervention toggle on/off

options in () should be there but arent, options in [] are there but should be somewhere else 

On the database connection screen:
cant type in user or password screen when selecting it

2022-06-19 13:22 UTC, shoekzema commented
I will not (not worth the time) fix the orders in the FF-menu and the controls config menu, because they are made by looping through the buttons based on the order of a struct type that is used in like 50 other places.

I won't state that the GuiOrder changed, because the order only matters with defaultkeysadd, which I did state was changed.

2022-06-19 15:06 UTC, suppergerrie2 approved these changes

2022-06-19 15:57 UTC, larsdekwant approved these changes

2022-06-19 15:58 UTC, merged