V22F-962 Fix memory leak and interventions
red-panda-productions/DAISI pull request #249
Opened 2022-06-22 20:11 UTC by larsdekwant

- Fixes the likely cause of `DAISI: ssgBase.cxx:78: virtual ssgBase::~ssgBase(): Assertion `refc == 0' failed.`, hasn't happened to me for 30min+ of testing the game.
- Fixed interventions that would not turn on again after restarting the game. This happened when the game was exited while interventions were toggled of via the button 'toggle interventions on/off'. This then left the internal mediator staat on on `INTERVENTION_TYPE_NO_SIGNALS`. This is now fixed.

2022-06-22 20:12 UTC, KungFuDonkey approved these changes

2022-06-23 08:12 UTC, KungFuDonkey requested changes
DAISI: ssgBase.cxx:78: virtual ssgBase::~ssgBase(): Assertion `refc == 0' failed.

On Linux, probably due to IndicatorConfig

2022-06-23 08:31 UTC, KungFuDonkey approved these changes

2022-06-23 08:34 UTC, suppergerrie2 approved these changes

2022-06-23 08:45 UTC, merged